---
title: "analysis_phpda"
author: "Hitomi Kariya"
date: "9/5/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(foreign)
library(data.table)
library(tidyverse)
library(survey)
library(multcomp)
setwd("~/Documents/MPH/Practicum/Data_Analysis")
rm(list=ls())
```

### Import df15_sub
```{r}
#df15_sub = a subset of data filtered to the related variables in Wasington state
df15 <- read.csv("df15_sub.csv")
colnames(df15)
head(df15)
df15$HPVADVC2 <- NULL #Delete since it has only NA
```

#Check for missing
```{r}
sapply(df15, function(x) sum(is.na(x)))
```

# Check for Proportion of those who did not meet the guidlines
```{r}
########## Unweighted
#Asian
n_notmet <- df15 %>% filter(X_RACE == 4) %>% filter(HADPAP2 == 2 | (HADPAP2 == 1 & (LASTPAP2 == 4 | LASTPAP2 == 5 | LASTPAP2 == 7)) | HADPAP2 == 7) %>% nrow()

n_total <- df15 %>% filter(X_RACE == 4) %>% filter(HADPAP2 == 1 | HADPAP2 == 2 | HADPAP2 == 7 | HADPAP2 == 9) %>% nrow() #Including the refused in the total
n_notmet/n_total

#White
n_notmet <- df15 %>% filter(X_RACE == 1) %>% filter(HADPAP2 == 2 | (HADPAP2 == 1 & (LASTPAP2 == 4 | LASTPAP2 == 5 | LASTPAP2 == 7)) | HADPAP2 == 7) %>% nrow()

n_total <- df15 %>% filter(X_RACE == 1) %>% filter(HADPAP2 == 1 | HADPAP2 == 2 | HADPAP2 == 7 | HADPAP2 == 9) %>% nrow() #Including the refused in the total
n_notmet/n_total

n_notmet <- df15 %>% filter(X_RACE == 2) %>% filter(HADPAP2 == 2 | (HADPAP2 == 1 & (LASTPAP2 == 4 | LASTPAP2 == 5 | LASTPAP2 == 7)) | HADPAP2 == 7) %>% nrow()

n_total <- df15 %>% filter(X_RACE == 2) %>% filter(HADPAP2 == 1 | HADPAP2 == 2 | HADPAP2 == 7 | HADPAP2 == 9) %>% nrow() #Including the refused in the total
n_notmet/n_total

#Hispanic
n_notmet <- df15 %>% filter(X_RACE == 8) %>% filter(HADPAP2 == 2 | (HADPAP2 == 1 & (LASTPAP2 == 4 | LASTPAP2 == 5 | LASTPAP2 == 7)) | HADPAP2 == 7) %>% nrow()

n_total <- df15 %>% filter(X_RACE == 8) %>% filter(HADPAP2 == 1 | HADPAP2 == 2 | HADPAP2 == 7 | HADPAP2 == 9) %>% nrow() #Including the refused in the total
n_notmet/n_total

#X_RACE: 1 = White, 2 = Black, 4 = Asian, 8 = Hispanic
```

# Prepare for the analysis
```{r}
########## Race Asian as Reference
#Originally coded as...
#X_RACE: 1 = White, 2 = Black, 4 = Asian, 8 = Hispanic

#Now coding into...
#race: 0 = Asian, 1 = White, 2 = Black, 3 = Hispanic, 4 = Others

df15$race <- ifelse(df15$X_RACE == 1, 1, NA) #White = 1
df15$race <- ifelse(df15$X_RACE == 2, 2, df15$race) #Black = 2
df15$race <- ifelse(df15$X_RACE == 8, 3, df15$race) #Hispanic = 3
df15$race <- ifelse(df15$X_RACE == 4, 0, df15$race) #Asian = 0
df15$race <- ifelse(df15$X_RACE == 3 | df15$X_RACE == 5 | df15$X_RACE == 6 | df15$X_RACE == 7, 4, df15$race) #Others = 4
head(df15$race)
df15$race <- as.factor(df15$race)
table(df15$race)

########## Education
#Originally coded as...
#???

#Now coding into...
#education: 0 = High school & less, 1 = college & more

df15$education <- ifelse(df15$EDUCA == c(1:4), 0, 1)
#High school & less = 0, college & more = 1
df15$education <- ifelse(df15$EDUCA == 9, NA, df15$education)
#Excluding the refused
table(df15$education)
sum(is.na(df15$education))
head(df15)

########## Age
#Originally coded as a fourteen-level category
#coding into 5 categories
df15$age <- ifelse(df15$X_AGEG5YR == 1 | df15$X_AGEG5YR == 2, 0, NA) #18-29 = 0
df15$age <- ifelse(df15$X_AGEG5YR == 3 | df15$X_AGEG5YR == 4, 1, df15$age) #30-39 = 1
df15$age <- ifelse(df15$X_AGEG5YR == 5 | df15$X_AGEG5YR == 6, 2, df15$age) #40-49 = 2
df15$age <- ifelse(df15$X_AGEG5YR == 7 | df15$X_AGEG5YR == 8, 3, df15$age) #50-59 = 3
df15$age <- ifelse(df15$X_AGEG5YR == 9, 4, df15$age) #60-64 = 4
df15$age <- ifelse(df15$X_AGEG5YR >= 10, 5, df15$age) #65- = 5
table(df15$age)

#coding into 2 categories
df15$age <- ifelse(df15$age == 0, 0, ifelse(df15$age >= 1 & df15$age <= 4, 1, ifelse(df15$age == 5, NA, NA)))
table(df15$age)
#18 - 29 = 0, 30 - 64 = 1, 65+ = NA

########## Age
#Originally recoding
#1. Re-categorizing the variable
# df15$age <- ifelse(df15$X_AGE_G == 1, 0, NA) #18-24
# df15$age <- ifelse(df15$X_AGE_G == 2, 1, df15$age) #25-34
# df15$age <- ifelse(df15$X_AGE_G == 3, 2, df15$age) #35-44
# df15$age <- ifelse(df15$X_AGE_G == 4, 3, df15$age) #45-54
# df15$age <- ifelse(df15$X_AGE_G == 5, 4, df15$age) #55-64
# df15$age <- ifelse(df15$X_AGE_G == 6, 5, df15$age) #65-
# class(df15$age)
# df15$age <- as.factor(df15$age)
# table(df15$age)
# 
# #2. Make it as Binary
# df15$age_binary <- ifelse(df15$age == 0 |df15$age == 1, 0, NA)
# df15$age_binary <- ifelse(df15$age == 2 |df15$age == 3 |df15$age == 4 |df15$age == 5, 1, df15$age_binary)
# class(df15$age_binary)
# df15$age_binary <- as.factor(df15$age_binary)
# table(df15$age_binary)
# #age_binary: 0 = 18 - 34, 1 = 35 and older

########## Outcome (Cervical Screening)

#Originally coded as...
#HADPAP2 == 2 = No (Haven't ever had a Pap test)
#HADPAP2 == 1 = Yes (Have ever had a Pap test)
#HADPAP2 == 7 = Don't know/Not sure ---> #Included Don't know as No (0)
#HADPAP2 == 9 = Refused

#LASTPAP2 == 4 = Had a Pap test within the past 5 years
#LASTPAP == 5 = Had a Pap test 5 or more years ago 
#LASTPAP == 7 = Don't know/not sure 

#Now coding into...
#Not recieving a screening within 3 years = 0
#Have received a screening withing 3 years = 1

df15$cervical_sc <- ifelse(df15$HADPAP2 == 2 | (df15$HADPAP2 == 1 & (df15$LASTPAP2 == 4 | df15$LASTPAP2 == 5 | df15$LASTPAP2 == 7)) | df15$HADPAP2 == 7, 0, NA)

df15$cervical_sc <- ifelse(df15$HADPAP2 == 1 & (df15$LASTPAP2 == 1 | df15$LASTPAP2 == 2 | df15$LASTPAP2 == 3), 1, df15$cervical_sc)

table(df15$cervical_sc)
sum(is.na(df15$cervical_sc))

### Checking the proportion of not receiving if it meets the proportion King county showed at the website
#These proportions are unweighted
not_recieving_asian <- df15 %>% filter(race == 3) %>% filter (cervical_sc == 0) %>% nrow()
total_asian <- df15 %>% filter(race == 3) %>% filter(HADPAP2 == 1 | HADPAP2 == 2 | HADPAP2 == 7) %>% nrow()
not_recieving_asian/total_asian

not_recieving_white <- df15 %>% filter(race == 0) %>% filter (cervical_sc == 0) %>% nrow()
total_white <- df15 %>% filter(race == 0) %>% filter(HADPAP2 == 1 | HADPAP2 == 2 | HADPAP2 == 7) %>% nrow()
not_recieving_white/total_white

########## Exposure (Marriage status)
#Originally coded as...
#MARITAL == 1 = Married
#MARITAL == 2 = Divorced
#MARITAL == 3 = Widowed
#MARITAL == 4 = Separated
#MARITAL == 5 = Never Married
#MARITAL == 6 = Unmarried couple
#MARITAL == 9 = Refused

#Now coding into...
#Never married = 0
#Married & Marriage experience & Unmarried couple = 1
#Refused will be NA

df15$marriage <- ifelse(df15$MARITAL == 5, 0, NA)
df15$marriage <- ifelse(df15$MARITAL == 1 | df15$MARITAL == 2 | df15$MARITAL == 3 | df15$MARITAL == 4 | df15$MARITAL == 6, 1, df15$marriage)

table(df15$marriage)
sum(is.na(df15$marriage))

########## Exposure (Mammogram experience)
#Originally coded as...
#HADMAM == 2 = No (Haven't ever had a HADMAM test)
#HADMAM == 1 = Yes (Have ever had a HADMAM test)
#HADMAM == 7 = Don't know/Not sure
#HADMAM == 9 = Refused

#Now conding into...
#Not recieving a mammogram within 3 years = 0
#Have received a mammogram withing 3 years = 1

df15$mammogram <- ifelse(df15$HADMAM == 2 | (df15$HADMAM == 1 & (df15$HOWLONG == 4 | df15$HOWLONG == 5 | df15$HOWLONG == 7)) | df15$HADMAM == 7, 0, NA)

df15$mammogram <- ifelse(df15$HADMAM == 1 & (df15$HOWLONG == 1 | df15$HOWLONG == 2 | df15$HOWLONG == 3), 1, df15$mammogram)

table(df15$mammogram)
sum(is.na(df15$mammogram))

########## Exposure (Employment)
#Originally coded as...
#EMPLOY1 == 1 = Employed for wages
#EMPLOY1 == 2 = Self-employed
#EMPLOY1 == 3 = Out of work for 1 year or more
#EMPLOY1 == 4 = Out of work for less than 1 year
#EMPLOY1 == 5 = A homemaker
#EMPLOY1 == 6 = A student
#EMPLOY1 == 7 = Retired
#EMPLOY1 == 8 = Unable to work
#EMPLOY1 == 9 = Refused

#Now coding into...
#Employed = 0 (1, 2, 5, 6)
#Unemployed = 1 (3, 4, 8)
#Retired & Refused will be NA

df15$employment <- ifelse(df15$EMPLOY1 == 1 | df15$EMPLOY1 == 2 | df15$EMPLOY1 == 5 | df15$EMPLOY1 == 6, 0, NA)

df15$employment <- ifelse(df15$EMPLOY1 == 3 | df15$EMPLOY1 == 4 | df15$EMPLOY1 == 8, 1, df15$employ)

table(df15$employment)
sum(is.na(df15$employment))

########## Exposure (Healthcare)
#Originally coded as...
#HLTHPLN1 == 1 = Yes (Have healthcare coverage)
#HLTHPLN1 == 2 = No (Don't have healthcare coverage)
#HLTHPLN1 == 7 = Don't know/Not sure
#HLTHPLN1 == 9 = Refused

#Now coding into...
#Have healthcare = 0
#Don't have healthcare = 1
#Don't know/Not sure & Refused will be NA

df15$healthcare <- ifelse(df15$HLTHPLN1 == 1, 0, NA)
df15$healthcare <- ifelse(df15$HLTHPLN1 == 2, 1, df15$healthcare)

table(df15$healthcare)
sum(is.na(df15$healthcare))
```

### Population characteristics (Weighted)
### Create survey design
```{r}
options(survey.lonely.psu = "adjust")
design <- svydesign(data = df15, id=~X_PSU, strata = ~strata, weight = ~weight, nest = TRUE)

########## Sample size
table(df15$X_RACE)
#X_RACE: 1 = White, 2 = Black, 4 = Asian, 8 = Hispanic

table(df15$race) #Sample size (unweighted)
#race: White = 1, Black = 2, Hispanic = 3, Asian = 0, #Others = 4
prop.table(svytable(~race, design = design)) #Weighted proportion

########## Population characteristics
##age_binary: 0 = 18 -29 years old 1 = 30 - 64 years ~
prop.table(svytable(~age, subset(design, race == 0))) #Asian
prop.table(svytable(~age, subset(design, race == 1))) #White
prop.table(svytable(~age, subset(design, race == 2))) #Black
prop.table(svytable(~age, subset(design, race == 3))) #Hispanic
prop.table(svytable(~age, subset(design, race == 4))) #Other


  
##education: High school & less = 0, college & more = 1
prop.table(svytable(~education, subset(design, race == 0))) #Asian
prop.table(svytable(~education, subset(design, race == 1))) #White
prop.table(svytable(~education, subset(design, race == 2))) #Black
prop.table(svytable(~education, subset(design, race == 3))) #Hispanic
prop.table(svytable(~education, subset(design, race == 4))) #Other

##marriage: #Never married = 0, Married & Marriage experience & Unmarried couple = 1
prop.table(svytable(~marriage, subset(design, race == 0))) #Asian
prop.table(svytable(~marriage, subset(design, race == 1))) #White
prop.table(svytable(~marriage, subset(design, race == 2))) #Black
prop.table(svytable(~marriage, subset(design, race == 3))) #Hispanic
prop.table(svytable(~marriage, subset(design, race == 4))) #Other

########## Weighted Prevalence of receiving a screening within three years
prop.table(svytable(~cervical_sc, subset(design, race == 0))) #Asian
prop.table(svytable(~cervical_sc, subset(design, race == 1))) #White
prop.table(svytable(~cervical_sc, subset(design, race == 2))) #Black
prop.table(svytable(~cervical_sc, subset(design, race == 3))) #Hispanic
prop.table(svytable(~cervical_sc, subset(design, race == 4))) #Other

########## Weighted Prevalence of receiving a screening within three years by marriage status
prop.table(svytable(~cervical_sc, subset(design, race == 0 & marriage == 0))) #Asian unmarried
prop.table(svytable(~cervical_sc, subset(design, race == 0 & marriage == 1))) #Asian Married

prop.table(svytable(~cervical_sc, subset(design, race == 1 & marriage == 0))) 
prop.table(svytable(~cervical_sc, subset(design, race == 1 & marriage == 1)))

prop.table(svytable(~cervical_sc, subset(design, race == 2 & marriage == 0))) 
prop.table(svytable(~cervical_sc, subset(design, race == 2 & marriage == 1)))

prop.table(svytable(~cervical_sc, subset(design, race == 3 & marriage == 0))) 
prop.table(svytable(~cervical_sc, subset(design, race == 3 & marriage == 1)))

prop.table(svytable(~cervical_sc, subset(design, race == 4 & marriage == 0))) 
prop.table(svytable(~cervical_sc, subset(design, race == 4 & marriage == 1)))
```

### Population characteristics (Unweighted)
```{r}
########## Population characteristics
##age_binary: 0 = ~34 years old 1 = 35 years ~
#Asian
age_0 <- df15 %>% filter(race == 0) %>% filter(age == 0) %>% nrow()
age_total <- df15 %>% filter(race == 0) %>% filter(age == 0|age == 1) %>% nrow()
age_0/age_total

#White
age_0 <- df15 %>% filter(race == 1) %>% filter(age == 0) %>% nrow()
age_total <- df15 %>% filter(race == 1) %>% filter(age == 0|age == 1) %>% nrow()
age_0/age_total

#Black
age_0 <- df15 %>% filter(race == 2) %>% filter(age == 0) %>% nrow()
age_total <- df15 %>% filter(race == 2) %>% filter(age == 0|age == 1) %>% nrow()
age_0/age_total

#Hispanic
age_0 <- df15 %>% filter(race == 3) %>% filter(age == 0) %>% nrow()
age_total <- df15 %>% filter(race == 3) %>% filter(age == 0|age == 1) %>% nrow()
age_0/age_total

#Other
age_0 <- df15 %>% filter(race == 4) %>% filter(age == 0) %>% nrow()
age_total <- df15 %>% filter(race == 4) %>% filter(age == 0|age == 1) %>% nrow()
age_0/age_total
  
##education: High school & less = 0, college & more = 1
#Asian
age_0 <- df15 %>% filter(race == 0) %>% filter(education == 0) %>% nrow()
age_total <- df15 %>% filter(race == 0) %>% filter(education == 0|education == 1) %>% nrow()
age_0/age_total

#White
age_0 <- df15 %>% filter(race == 1) %>% filter(education == 0) %>% nrow()
age_total <- df15 %>% filter(race == 1) %>% filter(education == 0|education == 1) %>% nrow()
age_0/age_total

#Black
age_0 <- df15 %>% filter(race == 2) %>% filter(education == 0) %>% nrow()
age_total <- df15 %>% filter(race == 2) %>% filter(education == 0|education == 1) %>% nrow()
age_0/age_total

#Hispanic
age_0 <- df15 %>% filter(race == 3) %>% filter(education == 0) %>% nrow()
age_total <- df15 %>% filter(race == 3) %>% filter(education == 0|education == 1) %>% nrow()
age_0/age_total

#Other
age_0 <- df15 %>% filter(race == 4) %>% filter(education == 0) %>% nrow()
age_total <- df15 %>% filter(race == 4) %>% filter(education == 0|education == 1) %>% nrow()
age_0/age_total

##marriage: #Never married = 0, Married & Marriage experience & Unmarried couple = 1
#Asian
age_0 <- df15 %>% filter(race == 0) %>% filter(marriage == 0) %>% nrow()
age_total <- df15 %>% filter(race == 0) %>% filter(marriage == 0|marriage == 1) %>% nrow()
age_0/age_total

#White
age_0 <- df15 %>% filter(race == 1) %>% filter(marriage == 0) %>% nrow()
age_total <- df15 %>% filter(race == 1) %>% filter(marriage == 0|marriage == 1) %>% nrow()
age_0/age_total

#Black
age_0 <- df15 %>% filter(race == 2) %>% filter(marriage == 0) %>% nrow()
age_total <- df15 %>% filter(race == 2) %>% filter(marriage == 0|marriage == 1) %>% nrow()
age_0/age_total

#Hispanic
age_0 <- df15 %>% filter(race == 3) %>% filter(marriage == 0) %>% nrow()
age_total <- df15 %>% filter(race == 3) %>% filter(marriage == 0|marriage == 1) %>% nrow()
age_0/age_total

#Other
age_0 <- df15 %>% filter(race == 4) %>% filter(marriage == 0) %>% nrow()
age_total <- df15 %>% filter(race == 4) %>% filter(marriage == 0|marriage == 1) %>% nrow()
age_0/age_total

########## Weighted Prevalence of receiving a screening within three years
#Asian
age_0 <- df15 %>% filter(race == 0) %>% filter(cervical_sc == 1) %>% nrow()
age_total <- df15 %>% filter(race == 0) %>% filter(cervical_sc == 0|cervical_sc == 1) %>% nrow()
age_0/age_total

#White
age_0 <- df15 %>% filter(race == 1) %>% filter(cervical_sc == 1) %>% nrow()
age_total <- df15 %>% filter(race == 1) %>% filter(cervical_sc == 0|cervical_sc == 1) %>% nrow()
age_0/age_total

#Black
age_0 <- df15 %>% filter(race == 2) %>% filter(cervical_sc == 1) %>% nrow()
age_total <- df15 %>% filter(race == 2) %>% filter(cervical_sc == 0|cervical_sc == 1) %>% nrow()
age_0/age_total

#Hispanic
age_0 <- df15 %>% filter(race == 3) %>% filter(cervical_sc == 1) %>% nrow()
age_total <- df15 %>% filter(race == 3) %>% filter(cervical_sc == 0|cervical_sc == 1) %>% nrow()
age_0/age_total

#Other
age_0 <- df15 %>% filter(race == 4) %>% filter(cervical_sc == 1) %>% nrow()
age_total <- df15 %>% filter(race == 4) %>% filter(cervical_sc == 0|cervical_sc == 1) %>% nrow()
age_0/age_total

########## Weighted Prevalence of receiving a screening within three years by marriage status
### Unmarried
#Asian
age_0 <- df15 %>% filter(race == 0) %>% filter(marriage == 0) %>% filter(cervical_sc == 1) %>% nrow()
age_total <- df15 %>% filter(race == 0) %>% filter(marriage == 0) %>% filter(cervical_sc == 1|cervical_sc == 0) %>% nrow()
age_0/age_total

#White
age_0 <- df15 %>% filter(race == 1) %>% filter(marriage == 0) %>% filter(cervical_sc == 1) %>% nrow()
age_total <- df15 %>% filter(race == 1) %>% filter(marriage == 0) %>% filter(cervical_sc == 1|cervical_sc == 0) %>% nrow()
age_0/age_total

#Black
age_0 <- df15 %>% filter(race == 2) %>% filter(marriage == 0) %>% filter(cervical_sc == 1) %>% nrow()
age_total <- df15 %>% filter(race == 2) %>% filter(marriage == 0) %>% filter(cervical_sc == 1|cervical_sc == 0) %>% nrow()
age_0/age_total

#Hispanic
age_0 <- df15 %>% filter(race == 3) %>% filter(marriage == 0) %>% filter(cervical_sc == 1) %>% nrow()
age_total <- df15 %>% filter(race == 3) %>% filter(marriage == 0) %>% filter(cervical_sc == 1|cervical_sc == 0) %>% nrow()
age_0/age_total

#Other
age_0 <- df15 %>% filter(race == 4) %>% filter(marriage == 0) %>% filter(cervical_sc == 1) %>% nrow()
age_total <- df15 %>% filter(race == 4) %>% filter(marriage == 0) %>% filter(cervical_sc == 1|cervical_sc == 0) %>% nrow()
age_0/age_total

### Married
#Asian
age_0 <- df15 %>% filter(race == 0) %>% filter(marriage == 1) %>% filter(cervical_sc == 1) %>% nrow()
age_total <- df15 %>% filter(race == 0) %>% filter(marriage == 1) %>% filter(cervical_sc == 1|cervical_sc == 0) %>% nrow()
age_0/age_total

#White
age_0 <- df15 %>% filter(race == 1) %>% filter(marriage == 1) %>% filter(cervical_sc == 1) %>% nrow()
age_total <- df15 %>% filter(race == 1) %>% filter(marriage == 1) %>% filter(cervical_sc == 1|cervical_sc == 0) %>% nrow()
age_0/age_total

#Black
age_0 <- df15 %>% filter(race == 2) %>% filter(marriage == 1) %>% filter(cervical_sc == 1) %>% nrow()
age_total <- df15 %>% filter(race == 2) %>% filter(marriage == 1) %>% filter(cervical_sc == 1|cervical_sc == 0) %>% nrow()
age_0/age_total

#Hispanic
age_0 <- df15 %>% filter(race == 3) %>% filter(marriage == 1) %>% filter(cervical_sc == 1) %>% nrow()
age_total <- df15 %>% filter(race == 3) %>% filter(marriage == 1) %>% filter(cervical_sc == 1|cervical_sc == 0) %>% nrow()
age_0/age_total

#Other
age_0 <- df15 %>% filter(race == 4) %>% filter(marriage == 1) %>% filter(cervical_sc == 1) %>% nrow()
age_total <- df15 %>% filter(race == 4) %>% filter(marriage == 1) %>% filter(cervical_sc == 1|cervical_sc == 0) %>% nrow()
age_0/age_total

```

# Logistic Regression (Race as an EM)
```{r}
df15$marriage <- as.factor(df15$marriage)
df15$education <- as.factor(df15$education)
df15$age <- as.factor(df15$age)
df15$race <- as.factor(df15$race)
head(df15)
df15$employment <- as.factor(df15$employment)
head(df15)
df15$healthcare <- as.factor(df15$healthcare)
head(df15)

########## Aim1
options(survey.lonely.psu = "adjust")
design <- svydesign(data = df15, id=~X_PSU, strata = ~strata, weight = ~weight, nest = TRUE)

ratio <- svyglm(cervical_sc ~ as.factor(marriage) + as.factor(education) + as.factor(age) + as.factor(race) + as.factor(employment) + as.factor(healthcare), design = design, family = binomial)

summary(ratio)
exp(coef(ratio))
exp(confint(ratio))#When ref = white, OR of receving a screening within 3 years comparing Asian to Whites is 0.56,
#where Asians have 44% lower odds of receiving.

# Likelihood ratio test
nested <- svyglm(cervical_sc ~ as.factor(marriage) + as.factor(education) + as.factor(age), design = design, family = binomial)

anova(nested, ratio, test = "Chisq", method = "LRT")
#Since the p-value is 2.4664e-08, there is an association between screening behaviro and race.

########## Aim2
#Interaction marriage*race?

#not including employment and healthcare
#kesu
kesu <- svyglm(cervical_sc ~ as.factor(marriage) + as.factor(education) + as.factor(age) + as.factor(race) +  as.factor(marriage)*as.factor(race), design = design, family = binomial)

summary(kesu)
confint(kesu)

exp(coef(kesu))
exp(confint(kesu))

exp(-1.1245)
-1.1245 + 1.8968
exp(0.7723)
#kesu

#including employment and healthcare
ratio_interaction <- svyglm(cervical_sc ~ as.factor(marriage) + as.factor(education) + as.factor(age) + as.factor(race) + as.factor(employment) + as.factor(healthcare) + as.factor(marriage)*as.factor(race), design = design, family = binomial)

summary(ratio_interaction)
confint(ratio_interaction)

exp(coef(ratio_interaction))
exp(confint(ratio_interaction))

# Get estimate for Asian
#OR_asian <- glht(ratio_interaction, "factor(marriage)1 + factor(marriage * race)3 == 0")
#glht function doesn't work with as.factor
###Look at the Slide11_BIOST513 page 15

#Get estimate
b0 <- -0.9310 #coef: intercept
b1 <- 1.8671 #coef: (marriage)1

b4_white <- 1.3409 #coef: (race)1
b7_white <- -1.2448 #coef: (marriage)1:(race)1

b4_black <- 3.0264 
b7_black <- -2.3243

b4_hispanic <- 1.3290
b7_hispanic <- -0.5110

b4_other <- 1.0405
b7_other <- -0.9758

#Asian
exp(b1) #Exp(coef: intercept + (marriage)1)

#White
exp(b1 + b7_white)

#Black
exp(b1 + b7_black)

#Hispanic
exp(b1 + b7_hispanic)

#Other
exp(b1 + b7_other)

# Likelihood ratio test
nested <- svyglm(cervical_sc ~ as.factor(marriage) + as.factor(education) + as.factor(age_binary) + as.factor(race), design = design, family = binomial)

anova(nested, ratio_interaction, test = "Chisq", method = "LRT")
# Since the p-value is p= 0.084625, there is no difference in the association of the screening behavior and marriage status by race.
```

# Logistic Regression (Only for Asian population)
```{r}
###Only for Asian population (Age as Binary)
df15_asian <- df15 %>% filter (X_RACE == 4)
head(df15_asian)
options(survey.lonely.psu = "adjust")
design_asian <- svydesign(data = df15_asian, id=~X_PSU, strata = ~strata, weight = ~weight, nest = TRUE)

ratio_asian <- svyglm(cervical_sc ~ as.factor(marriage) + as.factor(education) + as.factor(age) + as.factor(mammogram) + as.factor(employment) + as.factor(healthcare), design = design_asian, family = binomial)
summary(ratio_asian)
exp(coef(ratio_asian))
exp(confint(ratio_asian))
```